import { Colors } from '@/components/deathnotice';

export const MAPS = [
	'de_vertigo',
	'de_ancient',
	'de_anubis',
	'de_dust2',
	'de_inferno',
	'de_mirage',
	'de_nuke',
	'de_overpass',
	'de_train'
] as const;

export const DEFAULT_COLORS: Colors = {
	ctColor: '#6f9ce6',
	tColor: '#eabe54',
	borderColor: '#e10000',
	bgColor: '#000000',
	bgOpacity: 40,
	localBgColor: '#000000',
	localBgOpacity: 90
};

export type Resolution = { width: number; height: number };
export const DEFAULT_RESOLUTION: Resolution = { width: 1920, height: 1080 };

export const WEAPONS = {
	ak47: 'AK-47',
	aug: 'AUG',
	awp: 'AWP',
	bizon: 'PP-Bizon',
	cz75a: 'CZ75-Auto',
	deagle: 'Desert Eagle',
	elite: 'Dual Berettas',
	famas: 'FAMAS',
	fiveseven: 'Five-SeveN',
	g3sg1: 'G3SG1',
	galilar: 'Galil AR',
	glock: 'Glock-18',
	hkp2000: 'P2000',
	m249: 'M249',
	m4a1: 'M4A4',
	m4a1_silencer: 'M4A1-S',
	m4a1_silencer_off: 'M4A1-S No Silencer',
	mac10: 'MAC-10',
	mag7: 'MAG-7',
	mp5sd: 'MP5-SD',
	mp7: 'MP7',
	mp9: 'MP9',
	negev: 'Negev',
	nova: 'Nova',
	p90: 'P90',
	p250: 'P250',
	revolver: 'R8 Revolver',
	sawedoff: 'Sawed-Off',
	scar20: 'Scar20',
	sg556: 'SG 553',
	ssg08: 'SSG 08',
	tec9: 'Tec-9',
	ump45: 'UMP-45',
	usp_silencer: 'USP-S',
	usp_silencer_off: 'USP-S No Silencer',
	xm1014: 'XM1014',
	taser: 'Zeus x27',
	flashbang: 'Flashbang',
	smokegrenade: 'Smoke Grenade',
	hegrenade: 'HE Grenade',
	molotov: 'Molotov',
	decoy: 'Decoy Grenade',
	incgrenade: 'Incendiary Grenade',
	planted_c4: 'Explosion',
	inferno: 'Fire',
	knife: 'CT Knife',
	knife_t: 'T Knife',
	knifegg: 'Gold Knife',
	bayonet: 'Bayonet',
	knife_flip: 'Flip Knife',
	knife_gut: 'Gut Knife',
	knife_css: 'Classic Knife',
	knife_m9_bayonet: 'M9 Bayonet',
	knife_karambit: 'Karambit',
	knifet_actical: 'Huntsman Knife',
	knife_butterfly: 'Butterfly Knife',
	knife_falchion: 'Falchion Knife',
	knife_push: 'Shadow Daggers',
	knife_bowie: 'Bowie Knife',
	knife_cord: 'Paracord Knife',
	knife_canis: 'Survival Knife',
	knife_ursus: 'Ursus Knife',
	knife_gypsy_jackknife: 'Navaja Knife',
	knife_outdoor: 'Nomad Knife',
	knife_widowmaker: 'Talon Knife',
	knife_stiletto: 'Stiletto Knife',
	knife_skeleton: 'Skeleton Knife',
	knife_kukri: 'Kukri Knife'
};
